### ISSUE TITLE
Add support for Grief Prevention

### ISSUE THREAD

**Issue by theLastHero** [judgetread/PlayerWarpGUI#1]
Add support for grief prevention plugin so players can only set warps if.
- in a claim
- in a claim they are owner of
- in a claim they are trusted in

Also a option to remove any warps that are in a claim, when a claim is deleted.

**Comment by judgetread** [comment]
@theLastHero 
Completed request. #b2f708d51fd7837015f6f5bd4b53527b1e573a2f
